name: Upload requirements
on: 
  workflow_dispatch:
    inputs:
      tags:
        description: 'tags to create build'
jobs:
  build-windows-10:
    runs-on: windows-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v4
      with:
        ref: main
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'         
    - name: Run
      shell: bash
      run: |
        ./install.sh
        date=$(date '+%Y%m%d%H%M%S')
        "/c/Program Files/7-Zip/7z.exe" a -t7z -mx=1 -m0=LZMA2 -md=256k -mfb=32 -ms=32m -mmt=4 -v40m requirements-windows-$date.z packages
    - name: create release and upload assets
      uses: softprops/action-gh-release@v2
      with:
        files: |
          requirements-*
        tag_name: ${{ github.event.inputs.tags }}
  build-windows-12:
    runs-on: windows-latest
    needs: build-windows-10
    permissions: write-all
    steps:
    - uses: actions/checkout@v4
      with:
        ref: main
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'         
    - name: Run
      shell: bash
      run: |
        ./install.sh
        date=$(date '+%Y%m%d%H%M%S')
        "/c/Program Files/7-Zip/7z.exe" a -t7z -mx=1 -m0=LZMA2 -md=256k -mfb=32 -ms=32m -mmt=4 -v40m requirements-windows-$date.z packages
    - name: create release and upload assets
      uses: softprops/action-gh-release@v2
      with:
        files: |
          requirements-*
        tag_name: ${{ github.event.inputs.tags }}
  build-ubuntu:
    needs: build-windows-12
    runs-on: ubuntu-22.04
    permissions: write-all
    steps:
    - uses: actions/checkout@v4
      with:
        ref: main
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'         
    - name: Run
      run: |
        bash ./install.sh
        date=$(date '+%Y%m%d%H%M%S')
        7z a -t7z -mx=1 -m0=LZMA2 -md=256k -mfb=32 -ms=32m -mmt=4 -v40m requirements-ubuntu-$date.z packages
    - name: create release and upload assets
      uses: softprops/action-gh-release@v2
      with:
        files: |
          requirements-*
        tag_name: ${{ github.event.inputs.tags }}
